# Generated by Django 4.2.1 on 2023-07-01 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0001_initial'),
        ('panier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('delivery_address', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone', models.CharField(default='', max_length=20)),
                ('payment_method', models.CharField(default='', max_length=50)),
                ('statut', models.CharField(choices=[('Waiting_for_confirmation', 'Waiting for confirmation'), ('Confirmed', 'Confirmed'), ('In_the_course_of_delivery', 'In the course of delivery'), ('Delivered', 'Delivered')], default='Waiting_for_confirmation', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.commande')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats.plat')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='ordered_items',
            field=models.ManyToManyField(through='commande.CommandeItem', to='plats.plat'),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panier.panier'),
        ),
    ]
