# Generated by Django 4.2.1 on 2023-07-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commande.promotion'),
        ),
    ]
