# Generated by Django 4.2.1 on 2023-07-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_commande_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='reduction',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
