# Generated by Django 4.2.1 on 2023-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_alter_promotion_reduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
