# Generated by Django 4.2.1 on 2023-07-01 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListePlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits', models.ManyToManyField(to='plats.plat')),
                ('proprietaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat', models.ManyToManyField(related_name='paniers', through='panier.ListePlat', to='plats.plat')),
                ('proprietaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listeplat',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panier.panier'),
        ),
        migrations.AddField(
            model_name='listeplat',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats.plat'),
        ),
    ]
